export const field = {
    menu: [
        {
            link: 'admin.record.special.index',
            icon: "pi pi-home",
            label: "HOME",
            group: "record",
            order: 4,
        },
        {
            link: "admin.attendance.index",
            icon: "pi pi-building",
            label: "勤怠管理",
            group: "attendance",
            order: 2,
        },
        {
            link: 'admin.report.index',
            icon: "pi pi-table",
            label: "帳票管理",
            group: "report",
            order: 4,
        },
        {
            link: 'admin.locationcollect.index',
            icon: "pi pi-map-marker",
            label: "現場別集計",
            group: "locationcollect",
            order: 4,
        },
        {
            link: 'admin.consistency.index',
            icon: "pi pi-check-circle",
            label: "整合性確認",
            group: "consistency",
            order: 4,
        },
        {
            link: "admin.users.index",
            icon: "pi pi-user-plus",
            label: "ユーザー管理",
            group: "users",
            order: 5,
        },
        {
            link: null,
            icon: "pi pi-database",
            label: "マスター管理",
            group: "master",
            order: 5,
            children: [
                {
                    link: "admin.master.attendance.index",
                    icon: "pi pi-history",
                    label: "出勤管理（打刻データ)",
                    group: "master",
                    subGroup: "attendance",
                    order: 1,
                    table: "dakou_data",
                },
                {
                    link: "admin.master.timezone.index",
                    icon: "pi pi-clock",
                    label: "時間帯区分",
                    group: "master",
                    subGroup: "timezone",
                    order: 1,
                    table: "detail_time_breaks",
                },
                /*
                {
                    link: "admin.master.schedule.index",
                    icon: "pi pi-calendar-plus",
                    label: "作業予定管理",
                    group: "master",
                    subGroup: "schedule",
                    order: 3,
                    table: "schedules",
                },
                */
                {
                    link: "admin.master.location.index",
                    icon: "pi pi-map-marker",
                    label: "現場管理",
                    group: "master",
                    subGroup: "location",
                    order: 1,
                    table: "work_locations",
                },
                {
                    link: "admin.master.breaktime.index",
                    icon: "pi pi-bookmark",
                    label: "勤務形態管理",
                    group: "master",
                    subGroup: "breaktime",
                    order: 1,
                    table: "break_times",
                },
                {
                    link: "admin.master.occupation.index",
                    icon: "pi pi-flag",
                    label: "職種管理",
                    group: "master",
                    subGroup: "occupation",
                    order: 1,
                    table: "occupations",
                },
                {
                    link: "admin.master.work_contents.index",
                    icon: "pi pi-palette",
                    label: "作業内容",
                    group: "master",
                    subGroup: "work_contents",
                    order: 1,
                    table: "work_contents",
                },
                {
                    link: "admin.master.holiday.index",
                    icon: "pi pi-star",
                    label: "休日管理",
                    group: "master",
                    subGroup: "holiday",
                    order: 1,
                    table: "holidays",
                },
                {
                    link: "admin.master.attend_statuses.index",
                    icon: "pi pi-stopwatch",
                    label: "残業・早退・遅刻",
                    group: "master",
                    subGroup: "attend_statuses",
                    order: 1,
                    table: "attend_statuses",
                },
                {
                    link: "admin.master.support_company.index",
                    icon: "pi pi-thumbs-up",
                    label: "応援に来てもらう会社",
                    group: "master",
                    subGroup: "support_company",
                    order: 1,
                    table: "support_companies",
                },
                {
                    link: "admin.master.supported_company.index",
                    icon: "pi pi-thumbs-up-fill",
                    label: "応援に行く先の会社",
                    group: "master",
                    subGroup: "supported_company",
                    order: 1,
                    table: "supported_companies",
                },
                {
                    link: "admin.master.organization.index",
                    icon: "pi pi-sitemap",
                    label: "組織",
                    group: "master",
                    subGroup: "organization",
                    order: 1,
                    table: "organizations",
                },
                {
                    link: "admin.master.customer.index",
                    icon: "pi pi-users",
                    label: "得意先",
                    group: "master",
                    subGroup: "customer",
                    order: 1,
                    table: "customers",
                },
                
            ],
        },
        {
            link: 'admin.base.index',
            icon: "pi pi-users",
            label: "管理者設定",
            group: "base",
            order: 6,
        },
        {
            link: 'admin.dbmanage.index',
            icon: "pi pi-cog",
            label: "DB管理",
            group: "dbmanage",
            order: 7,
        },
    ],
};
export const driveRideOptions = [
    { value: 1, label: "運転" },
    { value: 2, label: "同乗" },
];
export const supportCompanyFlag = [
    { value: 0, label: "なし" },
    { value: 1, label: "応援に行った" },
    { value: 2, label: "応援に来てもらった" },
];
export const weekdays = ['日', '月', '火', '水', '木', '金', '土'] 
export const dpType = ['1日', '半日'];
